# Configuration of Hugo
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).


# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "/"

# Default language to use (if you setup multilingual support)
languageCode = "en-US"
defaultContentLanguage = "en"

# Title of your site
title = "Hugo Better Learn Documentation"

subtitle = "" # site tagline that appears below site title in masthead

# Name of Better Learn theme folder in `themes/`.
theme = ""

themesdir = "../.."
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

# Get last modified date for content from Git?
enableGitInfo = false

summaryLength = 30  # Listing summary length in words. Also, see `abstract_length` in `params.toml`.

paginate = 10  # Number of items per page in paginated lists.

title_separator = "-"

google_analytics = ""
google_tag_manager = ""

repository = ""
masthead_title = ""

search = "true" # true, false (default)
search_full_content = "false" # true, false (default)
search_provider = "lunr" # lunr (default), algolia, google

# SEO Related
google_site_verification = ""
bing_site_verification = ""
yandex_site_verification = ""
naver_site_verification = ""

# Social Sharing
twitter_username = ""
twitter_url = ""

facebook_username = ""
facebook_url = ""

[blackfriday]
   plainIDAnchors = true
   hrefTargetBlank = true

[params]
  editURL = "https://github.com/fatahdigital/better-learn/content/"
  description = "Documentation for Hugo Better Learn Theme"
  author = "Mathieu Cornic"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  custom_css = ["/css/"] # Your Custom css file Name File Add in Static/css/File_name.css
  themeVariant = "" # Added Theme Variant Color "default"  "Red", "Green", "Blue"

  images = [""] # Added Social Meadia SEO Image

  # Enter a copyright notice to display in the site footer.
  # To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
  copyright = ""

  # Local business type (optional)
  # If you entered "LocalBusiness" above, choose the type of business from https://schema.org/LocalBusiness#subtypes
  local_business_type = ""
 
  # Address format (choose from the [address_formats] list below or add you own to the list).
  address_format = "en-us"

  # Website type
  #   Improve how search engines understand your site.
  #   For personal sites, choose "Person".
  #   For organizations and projects, choose from https://schema.org/Organization#subtypes
  #   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
  site_type = "Organization"
  
[outputs]
  home = [ "HTML", "RSS", "JSON"]

# Configure the Markdown renderer.
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[Languages]
  [Languages.en]
    title = "Documentation for Hugo Better Learn Theme"
    weight = 1
    languageName = "English"

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
    identifier = "ds"
    url = "https://github.com/fatahdigital/better-learn/"
    weight = 10

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-camera'></i> Showcases"
    url = "showcase"
    weight = 11

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
    identifier = "hugodoc"
    url = "https://gohugo.io/"
    weight = 20

  [[Languages.en.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
    url = "/credits"
    weight = 30

  [Languages.fr]
    title = "Documentation du thème Hugo Better Learn"
    weight = 2
    languageName = "Français"

  [[Languages.fr.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> Repo GitHub"
    identifier = "ds"
    url = "https://github.com/fatahdigital/better-learn/"
    weight = 10

  [[Languages.fr.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-camera'></i> Vitrine"
    url = "/showcase"
    weight = 11

  [[Languages.fr.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bookmark'></i> Documentation Hugo"
    identifier = "hugodoc"
    url = "https://gohugo.io/"
    weight = 20

  [[Languages.fr.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bullhorn'></i> Crédits"
    url = "/credits"
    weight = 30

  [Languages.zh]
    title = "Hugo 主题的 Better Learn 文档"
    weight = 3
    languageName = "简体中文"

  [[Languages.zh.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> GitHub 仓库"
    identifier = "ds"
    url = "https://github.com/fatahdigital/better-learn/"
    weight = 10

  [[Languages.zh.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-camera'></i> 展示区"
    url = "/showcase"
    weight = 11

  [[Languages.zh.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bookmark'></i> Hugo 文档"
    identifier = "hugodoc"
    url = "https://gohugo.io/"
    weight = 20

  [[Languages.zh.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bullhorn'></i> 鸣谢"
    url = "/credits"
    weight = 30
